### ISSUE TITLE
Booting m1.small inception server... /Users/drnic/.rvm/gems/ruby-1.9.3-p448/gems/net-ssh-2.6.8/lib/net/ssh/transport/packet_stream.rb:87:in `next_packet': connection closed by remote host (Net::SSH::Disconnect)

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-community-attic/inception-server#53]
Occasionally get this error:

```
Booting m1.small inception server... /Users/drnic/.rvm/gems/ruby-1.9.3-p448/gems/net-ssh-2.6.8/lib/net/ssh/transport/packet_stream.rb:87:in `next_packet': connection closed by remote host (Net::SSH::Disconnect)
    from /Users/drnic/.rvm/gems/ruby-1.9.3-p448/gems/net-ssh-2.6.8/lib/net/ssh/transport/session.rb:172:in `block in poll_message'
    from /Users/drnic/.rvm/gems/ruby-1.9.3-p448/gems/net-ssh-2.6.8/lib/net/ssh/transport/session.rb:167:in `loop'
    from /Users/drnic/.rvm/gems/ruby-1.9.3-p448/gems/net-ssh-2.6.8/lib/net/ssh/transport/session.rb:167:in `poll_message'
    from /Users/drnic/.rvm/gems/ruby-1.9.3-p448/gems/net-ssh-2.6.8/lib/net/ssh/transport/session.rb:204:in `block in wait'
    from /Users/drnic/.rvm/gems/ruby-1.9.3-p448/gems/net-ssh-2.6.8/lib/net/ssh/transport/session.rb:202:in `loop'
    from /Users/drnic/.rvm/gems/ruby-1.9.3-p448/gems/net-ssh-2.6.8/lib/net/ssh/transport/session.rb:202:in `wait'
    from /Users/drnic/.rvm/gems/ruby-1.9.3-p448/gems/net-ssh-2.6.8/lib/net/ssh/transport/session.rb:81:in `initialize'
    from /Users/drnic/.rvm/gems/ruby-1.9.3-p448/gems/net-ssh-2.6.8/lib/net/ssh.rb:192:in `new'
    from /Users/drnic/.rvm/gems/ruby-1.9.3-p448/gems/net-ssh-2.6.8/lib/net/ssh.rb:192:in `start'
    from /Users/drnic/.rvm/gems/ruby-1.9.3-p448/gems/fog-1.15.0/lib/fog/core/ssh.rb:67:in `run'
    from /Users/drnic/.rvm/gems/ruby-1.9.3-p448/gems/fog-1.15.0/lib/fog/openstack/models/compute/server.rb:299:in `setup'
    from /Users/drnic/Projects/ruby/gems/inception-server/lib/inception/providers/clients/fog_provider_client.rb:198:in `bootstrap'
    from /Users/drnic/Projects/ruby/gems/inception-server/lib/inception/inception_server.rb:256:in `bootstrap_vm'
    from /Users/drnic/Projects/ruby/gems/inception-server/lib/inception/inception_server.rb:66:in `create'
    from /Users/drnic/Projects/ruby/gems/inception-server/lib/inception/cli.rb:119:in `perform_deploy'
    from /Users/drnic/Projects/ruby/gems/inception-server/lib/inception/cli.rb:34:in `deploy'
    from /Users/drnic/.rvm/gems/ruby-1.9.3-p448/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
    from /Users/drnic/.rvm/gems/ruby-1.9.3-p448/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
    from /Users/drnic/.rvm/gems/ruby-1.9.3-p448/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
    from /Users/drnic/.rvm/gems/ruby-1.9.3-p448/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
    from bin/inception:8:in `<main>'
```

**Comment by drnic** [comment]
`bundle exec bin/inception deploy  2.02s user 0.26s system 6% cpu 35.427 total`

**Comment by drnic** [comment]
Workaround was to add the following to `~/.ssh/config`

```
ConnectTimeout 60
```
