### ISSUE TITLE
trying to connect to vm while vm is not ready

### ISSUE THREAD

**Issue by ramonskie** [cloudfoundry-community-attic/inception-server#67]
i get the following error
this is because it tries to connect but the vm in openstack is still in spawning state
i think we need to arrange a wait_for option

```
Booting m1.small inception server... /home/klm21904/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:70:in `initialize': No route to host - connect(2) (Errno::EHOSTUNREACH)
    from /home/klm21904/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:70:in `open'
    from /home/klm21904/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:70:in `block in initialize'
    from /home/klm21904/.rbenv/versions/1.9.3-p429/lib/ruby/1.9.1/timeout.rb:69:in `timeout'
    from /home/klm21904/.rbenv/versions/1.9.3-p429/lib/ruby/1.9.1/timeout.rb:100:in `timeout'
    from /home/klm21904/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:67:in `initialize'
    from /home/klm21904/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/net-ssh-2.9.1/lib/net/ssh.rb:202:in `new'
    from /home/klm21904/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/net-ssh-2.9.1/lib/net/ssh.rb:202:in `start'
    from /home/klm21904/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/fog-core-1.24.0/lib/fog/core/ssh.rb:67:in `run'
    from /home/klm21904/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/fog-1.24.0/lib/fog/openstack/models/compute/server.rb:353:in `setup'
    from /home/klm21904/Workspace/inception-server/lib/inception/providers/clients/fog_provider_client.rb:198:in `bootstrap'
    from /home/klm21904/Workspace/inception-server/lib/inception/inception_server.rb:255:in `bootstrap_vm'
    from /home/klm21904/Workspace/inception-server/lib/inception/inception_server.rb:65:in `create'
    from /home/klm21904/Workspace/inception-server/lib/inception/cli.rb:131:in `perform_deploy'
    from /home/klm21904/Workspace/inception-server/lib/inception/cli.rb:36:in `deploy'
    from /home/klm21904/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /home/klm21904/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /home/klm21904/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /home/klm21904/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from bin/inception:8:in `<main>'
```

**Comment by ramonskie** [comment]
my temp solution was to add

```
sleep 60
```

https://github.com/cloudfoundry-community/inception-server/blob/master/lib/inception/providers/clients/fog_provider_client.rb#L195
