### ISSUE TITLE
master: ./script/build: line 44: go: command not found

### ISSUE THREAD

**Issue by aeneasr** [cloudfoundry-community-attic/inception-server#69]
```
$ git clone https://github.com/cloudfoundry-community/inception-server.git
$ cd inception-server
$ bundle
$ bundle install
$ bundle exec bin/inception deploy
1. AWS
2. OpenStack
3. vSphere
Choose your infrastructure: 1

Using provider AWS

Access key: ***
Secret key: ***

1. *US East (Northern Virginia) Region (us-east-1)
2. US West (Oregon) Region (us-west-2)
3. US West (Northern California) Region (us-west-1)
4. EU (Ireland) Region (eu-west-1)
5. EU (Frankfurt) Region (eu-central-1)
6. Asia Pacific (Singapore) Region (ap-southeast-1)
7. Asia Pacific (Sydney) Region (ap-southeast-2)
8. Asia Pacific (Tokyo) Region (ap-northeast-1)
9. South America (Sao Paulo) Region (sa-east-1)
10. China (Beijing) Region (cn-north-1)
Choose AWS region: 4

Confirming: Using AWS EC2/eu-west-1

Confirming: Using image ami-f6b11181

Preparing deployment settings

Using your git user.name (***)
Acquiring a public IP address... 52.16.136.**

Provision inception server

Reusing security group ssh
Booting m3.medium inception server... i-88a53c6c
Confirming ssh access to server... done
Provisioning 16Gb persistent disk for inception server... vol-32ad5634

Prepare inception server

knife solo prepare ubuntu@52.16.136.50 -i /Users/mrnice/.inception_server/ssh/inception -j '{"disk":{"mounted":true,"device":"/dev/xvdf"},"git":{"name":"****","email":"****"},"user":{"username":"ubuntu"},"fog":{"aws_access_key_id":"***","aws_secret_access_key":"***}}' -r 'bosh_inception'
WARNING: No knife configuration file found
Bootstrapping Chef...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18378  100 18378    0     0  25889      0 --:--:-- --:--:-- --:--:-- 25884
Downloading Chef 11.18.6 for ubuntu...
downloading https://www.opscode.com/chef/metadata?v=11.18.6&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
  to file /tmp/install.sh.8136/metadata.txt
trying wget...
url https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/13.04/x86_64/chef_11.18.6-1_amd64.deb
md5 f20d55682e4d6b3b23bb1b28fbfda7b3
sha256  13469f6b21a4a1077097ec8bb2fc999f410f2f9a7c6345f50a38a6b8da97baa6
downloaded metadata file looks valid...
downloading https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/13.04/x86_64/chef_11.18.6-1_amd64.deb
  to file /tmp/install.sh.8136/chef_11.18.6-1_amd64.deb
trying wget...
Comparing checksum with sha256sum...
Installing Chef 11.18.6
installing with dpkg...
Selecting previously unselected package chef.
(Reading database ... 51100 files and directories currently installed.)
Preparing to unpack .../chef_11.18.6-1_amd64.deb ...
Unpacking chef (11.18.6-1) ...
Setting up chef (11.18.6-1) ...
Thank you for installing Chef!
Generating node config './nodes/52.16.136.50.json'...
knife solo cook ubuntu@52.16.136.50 -i /Users/mrnice/.inception_server/ssh/inception -j '{"disk":{"mounted":true,"device":"/dev/xvdf"},"git":{"name":"****","email":"***"},"user":{"username":"ubuntu"},"fog":{"aws_access_key_id":"****","aws_secret_access_key":"***"}}' -r 'bosh_inception'
WARNING: No knife configuration file found
Running Chef on 52.16.136.50...
Checking Chef version...
Installing Berkshelf cookbooks to '/Users/mrnice/.berkshelf/knife-solo/a8ea89bb14e68956ac6c0e48aae3ca08b767019a'...
DEPRECATED: Your Berksfile contains a site location pointing to the Opscode Community Site (site :opscode). Site locations have been replaced by the source location. Change this to: 'source "https://supermarket.chef.io"' to remove this warning. For more information visit https://github.com/berkshelf/berkshelf/wiki/deprecated-locations
Resolving cookbook dependencies...
Fetching 'bosh_inception' from source at cookbooks/bosh_inception
Fetching 'chruby' from git://github.com/Atalanta/chef-chruby.git (at 1942bf8)
Fetching 'hub' from git://github.com/drnic/chef-hub.git (at master)
Fetching cookbook index from https://supermarket.chef.io...
Using 7-zip (1.0.2)
Using apt (2.6.1)
Using ark (0.9.0)
Using bosh_inception (0.1.0) from source at cookbooks/bosh_inception
Using chef_handler (1.1.6)
Using chruby (0.2.1) from git://github.com/Atalanta/chef-chruby.git (at 1942bf8)
Using hub (1.0.4) from git://github.com/drnic/chef-hub.git (at master)
Using ruby_build (0.8.0)
Using sudo (2.7.1)
Using user (0.3.0)
Using windows (1.36.6)
Vendoring 7-zip (1.0.2) to /Users/mrnice/.berkshelf/knife-solo/a8ea89bb14e68956ac6c0e48aae3ca08b767019a/7-zip
Vendoring apt (2.6.1) to /Users/mrnice/.berkshelf/knife-solo/a8ea89bb14e68956ac6c0e48aae3ca08b767019a/apt
Vendoring ark (0.9.0) to /Users/mrnice/.berkshelf/knife-solo/a8ea89bb14e68956ac6c0e48aae3ca08b767019a/ark
Vendoring bosh_inception (0.1.0) to /Users/mrnice/.berkshelf/knife-solo/a8ea89bb14e68956ac6c0e48aae3ca08b767019a/bosh_inception
Vendoring chef_handler (1.1.6) to /Users/mrnice/.berkshelf/knife-solo/a8ea89bb14e68956ac6c0e48aae3ca08b767019a/chef_handler
Vendoring chruby (0.2.1) to /Users/mrnice/.berkshelf/knife-solo/a8ea89bb14e68956ac6c0e48aae3ca08b767019a/chruby
Vendoring hub (1.0.4) to /Users/mrnice/.berkshelf/knife-solo/a8ea89bb14e68956ac6c0e48aae3ca08b767019a/hub
Vendoring ruby_build (0.8.0) to /Users/mrnice/.berkshelf/knife-solo/a8ea89bb14e68956ac6c0e48aae3ca08b767019a/ruby_build
Vendoring sudo (2.7.1) to /Users/mrnice/.berkshelf/knife-solo/a8ea89bb14e68956ac6c0e48aae3ca08b767019a/sudo
Vendoring user (0.3.0) to /Users/mrnice/.berkshelf/knife-solo/a8ea89bb14e68956ac6c0e48aae3ca08b767019a/user
Vendoring windows (1.36.6) to /Users/mrnice/.berkshelf/knife-solo/a8ea89bb14e68956ac6c0e48aae3ca08b767019a/windows
Uploading the kitchen...
WARNING: Local role_path './roles' does not exist
WARNING: Local data_bag_path './data_bags' does not exist
WARNING: Local environment_path './environments' does not exist
Generating solo config...
Running Chef: sudo chef-solo -c ~/chef-solo/solo.rb -j ~/chef-solo/dna.json
[2015-03-02T15:47:14+00:00] WARN: 
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
SSL validation of HTTPS requests is disabled. HTTPS connections are still
encrypted, but chef is not able to detect forged replies or man in the middle
attacks.

To fix this issue add an entry like this to your configuration file:


  # Verify all HTTPS connections (recommended)
  ssl_verify_mode :verify_peer

  # OR, Verify only connections to chef-server
  verify_api_cert true


To check your SSL configuration, or troubleshoot errors, you can use the
`knife ssl check` command like so:


  knife ssl check -c /home/ubuntu/chef-solo/solo.rb


* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

Starting Chef Client, version 11.18.6
[2015-03-02T15:47:16+00:00] WARN: found a directory chef-solo-search in the cookbook path, but it contains no cookbook files. skipping.
Compiling Cookbooks...
[2015-03-02T15:47:17+00:00] WARN: Cloning resource attributes for package[libsqlite3-dev] from prior resource (CHEF-3694)
[2015-03-02T15:47:17+00:00] WARN: Previous package[libsqlite3-dev]: /home/ubuntu/chef-solo/cookbooks-3/bosh_inception/recipes/packages.rb:19:in `block in from_file'
[2015-03-02T15:47:17+00:00] WARN: Current  package[libsqlite3-dev]: /home/ubuntu/chef-solo/cookbooks-3/bosh_inception/recipes/packages.rb:19:in `block in from_file'
[2015-03-02T15:47:17+00:00] WARN: Cloning resource attributes for package[git-core] from prior resource (CHEF-3694)
[2015-03-02T15:47:17+00:00] WARN: Previous package[git-core]: /home/ubuntu/chef-solo/cookbooks-3/bosh_inception/recipes/packages.rb:19:in `block in from_file'
[2015-03-02T15:47:17+00:00] WARN: Current  package[git-core]: /home/ubuntu/chef-solo/cookbooks-2/hub/recipes/default.rb:1:in `from_file'
[2015-03-02T15:47:17+00:00] WARN: Cloning resource attributes for package[curl] from prior resource (CHEF-3694)
[2015-03-02T15:47:17+00:00] WARN: Previous package[curl]: /home/ubuntu/chef-solo/cookbooks-3/bosh_inception/recipes/packages.rb:19:in `block in from_file'
[2015-03-02T15:47:17+00:00] WARN: Current  package[curl]: /home/ubuntu/chef-solo/cookbooks-2/ruby_build/recipes/default.rb:34:in `block in from_file'
[2015-03-02T15:47:17+00:00] WARN: Cloning resource attributes for package[git-core] from prior resource (CHEF-3694)
[2015-03-02T15:47:17+00:00] WARN: Previous package[git-core]: /home/ubuntu/chef-solo/cookbooks-2/hub/recipes/default.rb:1:in `from_file'
[2015-03-02T15:47:17+00:00] WARN: Current  package[git-core]: /home/ubuntu/chef-solo/cookbooks-2/ruby_build/recipes/default.rb:38:in `block in from_file'
[2015-03-02T15:47:17+00:00] WARN: Cloning resource attributes for package[rsync] from prior resource (CHEF-3694)
[2015-03-02T15:47:17+00:00] WARN: Previous package[rsync]: /home/ubuntu/chef-solo/cookbooks-3/bosh_inception/recipes/packages.rb:19:in `block in from_file'
[2015-03-02T15:47:17+00:00] WARN: Current  package[rsync]: /home/ubuntu/chef-solo/cookbooks-2/ark/recipes/default.rb:22:in `block in from_file'
[2015-03-02T15:47:17+00:00] WARN: Cloning resource attributes for directory[/home/ubuntu/workspace/microboshes] from prior resource (CHEF-3694)
[2015-03-02T15:47:17+00:00] WARN: Previous directory[/home/ubuntu/workspace/microboshes]: /home/ubuntu/chef-solo/cookbooks-3/bosh_inception/recipes/useful_dirs.rb:2:in `block in from_file'
[2015-03-02T15:47:17+00:00] WARN: Current  directory[/home/ubuntu/workspace/microboshes]: /home/ubuntu/chef-solo/cookbooks-3/bosh_inception/recipes/install_bosh.rb:8:in `from_file'
Converging 69 resources
Recipe: bosh_inception::mount_store_volume
  * bash[format /home/ubuntu/workspace partition] action run
    - execute "bash"  "/tmp/chef-script20150302-8624-yx7agy"
  * directory[/home/ubuntu/workspace] action create
    - create new directory /home/ubuntu/workspace
    - change mode from '' to '0755'
    - change owner from '' to 'root'
    - change group from '' to 'root'
  * mount[/home/ubuntu/workspace] action enable
    - enable /dev/xvdf
  * mount[/home/ubuntu/workspace] action mount
    - mount /dev/xvdf to /home/ubuntu/workspace
Recipe: bosh_inception::useful_dirs
  * directory[/home/ubuntu/workspace/microboshes] action create
    - create new directory /home/ubuntu/workspace/microboshes
    - change mode from '' to '0755'
    - change owner from '' to 'ubuntu'
    - change group from '' to 'ubuntu'
  * directory[/home/ubuntu/workspace/microboshes/deployments] action create
    - create new directory /home/ubuntu/workspace/microboshes/deployments
    - change mode from '' to '0755'
    - change owner from '' to 'ubuntu'
    - change group from '' to 'ubuntu'
  * directory[/home/ubuntu/workspace/deployments] action create
    - create new directory /home/ubuntu/workspace/deployments
    - change mode from '' to '0755'
    - change owner from '' to 'ubuntu'
    - change group from '' to 'ubuntu'
  * directory[/home/ubuntu/workspace/releases] action create
    - create new directory /home/ubuntu/workspace/releases
    - change mode from '' to '0755'
    - change owner from '' to 'ubuntu'
    - change group from '' to 'ubuntu'
  * directory[/home/ubuntu/workspace/repos] action create
    - create new directory /home/ubuntu/workspace/repos
    - change mode from '' to '0755'
    - change owner from '' to 'ubuntu'
    - change group from '' to 'ubuntu'
  * directory[/home/ubuntu/workspace/stemcells] action create
    - create new directory /home/ubuntu/workspace/stemcells
    - change mode from '' to '0755'
    - change owner from '' to 'ubuntu'
    - change group from '' to 'ubuntu'
  * directory[/home/ubuntu/workspace/systems] action create
    - create new directory /home/ubuntu/workspace/systems
    - change mode from '' to '0755'
    - change owner from '' to 'ubuntu'
    - change group from '' to 'ubuntu'
  * directory[/home/ubuntu/workspace/tmp] action create
    - create new directory /home/ubuntu/workspace/tmp
    - change mode from '' to '0755'
    - change owner from '' to 'ubuntu'
    - change group from '' to 'ubuntu'
  * directory[/home/ubuntu/workspace/bosh_cache] action create
    - create new directory /home/ubuntu/workspace/bosh_cache
    - change mode from '' to '0755'
    - change owner from '' to 'ubuntu'
    - change group from '' to 'ubuntu'
  * link[/home/ubuntu/.bosh_cache] action create
    - create symlink at /home/ubuntu/.bosh_cache to /home/ubuntu/workspace/bosh_cache
Recipe: apt::default
  * execute[apt-get-update] action run (skipped due to not_if)
  * execute[apt-get update] action nothing (skipped due to action :nothing)
  * execute[apt-get autoremove] action nothing (skipped due to action :nothing)
  * execute[apt-get autoclean] action nothing (skipped due to action :nothing)
  * package[update-notifier-common] action install (up to date)
  * execute[apt-get-update-periodic] action run (skipped due to only_if)
  * directory[/var/cache/local] action create
    - create new directory /var/cache/local
    - change mode from '' to '0755'
    - change owner from '' to 'root'
    - change group from '' to 'root'
  * directory[/var/cache/local/preseeding] action create
    - create new directory /var/cache/local/preseeding
    - change mode from '' to '0755'
    - change owner from '' to 'root'
    - change group from '' to 'root'
Recipe: bosh_inception::packages
  * package[build-essential] action install
    - install version 11.6ubuntu6 of package build-essential
  * package[libsqlite3-dev] action install
    - install version 3.8.2-1ubuntu2 of package libsqlite3-dev
  * package[curl] action install (up to date)
  * package[rsync] action install (up to date)
  * package[git-core] action install
    - install version 1:1.9.1-1ubuntu0.1 of package git-core
  * package[libmysqlclient-dev] action install
    - install version 5.5.41-0ubuntu0.14.04.1 of package libmysqlclient-dev
  * package[libxml2-dev] action install
    - install version 2.9.1+dfsg1-3ubuntu4.4 of package libxml2-dev
  * package[libxslt-dev] action install
    - install version 1.1.28-2build1 of package libxslt-dev
  * package[libpq-dev] action install
    - install version 9.3.6-0ubuntu0.14.04 of package libpq-dev
  * package[libsqlite3-dev] action install (up to date)
  * package[libcurl4-gnutls-dev] action install
    - install version 7.35.0-1ubuntu2.3 of package libcurl4-gnutls-dev
  * package[whois] action install
    - install version 5.1.1 of package whois
  * package[tmux] action install (up to date)
  * package[vim] action install (up to date)
Recipe: hub::default
  * package[git-core] action install (up to date)
  * directory[/usr/local/src] action create (up to date)
  * bash[install hub] action run

    ================================================================================
    Error executing action `run` on resource 'bash[install hub]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of "bash"  "/tmp/chef-script20150302-8624-10jm68b" ----
    STDOUT: 
    STDERR: Cloning into 'hub'...
    ./script/build: line 44: go: command not found
    cp: cannot stat 'hub': No such file or directory
    ---- End output of "bash"  "/tmp/chef-script20150302-8624-10jm68b" ----
    Ran "bash"  "/tmp/chef-script20150302-8624-10jm68b" returned 1

    Resource Declaration:
    ---------------------
    # In /home/ubuntu/chef-solo/cookbooks-2/hub/recipes/default.rb

     11: bash "install hub" do
     12:   user "root"
     13:   cwd node.hub.src_path
     14:   code <<-BASH
     15:   if [[ ! -d hub ]]; then
     16:     git clone #{node.hub.repo}
     17:     cd hub
     18:   else
     19:     cd hub
     20:     git pull origin master
     21:   fi
     22:   ./script/build
     23:   cp hub #{node.hub.install_path}
     24:   BASH
     25:   action :run
     26: end

    Compiled Resource:
    ------------------
    # Declared in /home/ubuntu/chef-solo/cookbooks-2/hub/recipes/default.rb:11:in `from_file'

    bash("install hub") do
      action [:run]
      retries 0
      retry_delay 2
      guard_interpreter :default
      command "\"bash\"  \"/tmp/chef-script20150302-8624-10jm68b\""
      backup 5
      cwd "/usr/local/src"
      returns 0
      user "root"
      code "  if [[ ! -d hub ]]; then\n    git clone https://github.com/github/hub.git\n    cd hub\n  else\n    cd hub\n    git pull origin master\n  fi\n  ./script/build\n  cp hub /usr/local\n"
      interpreter "bash"
      cookbook_name :hub
      recipe_name "default"
    end


Running handlers:
[2015-03-02T15:49:20+00:00] ERROR: Running exception handlers
Running handlers complete
[2015-03-02T15:49:20+00:00] ERROR: Exception handlers complete
[2015-03-02T15:49:20+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 25 resources updated in 125.502167812 seconds
[2015-03-02T15:49:20+00:00] ERROR: bash[install hub] (hub::default line 11) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of "bash"  "/tmp/chef-script20150302-8624-10jm68b" ----
STDOUT: 
STDERR: Cloning into 'hub'...
./script/build: line 44: go: command not found
cp: cannot stat 'hub': No such file or directory
---- End output of "bash"  "/tmp/chef-script20150302-8624-10jm68b" ----
Ran "bash"  "/tmp/chef-script20150302-8624-10jm68b" returned 1
[2015-03-02T15:49:20+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
ERROR: RuntimeError: chef-solo failed. See output above.
/Users/mrnice/.rvm/gems/ruby-2.0.0-p598@global/gems/rake-10.4.2/lib/rake/file_utils.rb:66:in `block in create_shell_runner': Command failed with status (100): [knife solo cook ubuntu@52.16.136.50 -i /Us...] (RuntimeError)
    from /Users/mrnice/.rvm/gems/ruby-2.0.0-p598@global/gems/rake-10.4.2/lib/rake/file_utils.rb:57:in `call'
    from /Users/mrnice/.rvm/gems/ruby-2.0.0-p598@global/gems/rake-10.4.2/lib/rake/file_utils.rb:57:in `sh'
    from /Users/mrnice/inception-server/lib/inception/inception_server_cookbook.rb:39:in `knife_solo'
    from /Users/mrnice/inception-server/lib/inception/inception_server_cookbook.rb:26:in `block in converge'
    from /Users/mrnice/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/fileutils.rb:125:in `chdir'
    from /Users/mrnice/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/fileutils.rb:125:in `cd'
    from /Users/mrnice/inception-server/lib/inception/inception_server_cookbook.rb:25:in `converge'
    from /Users/mrnice/inception-server/lib/inception/cli.rb:155:in `converge_cookbooks'
    from /Users/mrnice/inception-server/lib/inception/cli.rb:37:in `deploy'
    from /Users/mrnice/.rvm/gems/ruby-2.0.0-p598@global/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/mrnice/.rvm/gems/ruby-2.0.0-p598@global/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/mrnice/.rvm/gems/ruby-2.0.0-p598@global/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Users/mrnice/.rvm/gems/ruby-2.0.0-p598@global/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from bin/inception:8:in `<main>'
```

**Comment by aeneasr** [comment]
Same issue on us-east-1

**Comment by aeneasr** [comment]
okay so i tried it from a trusty32 vm as well with the same results, seems to be an issue with some dependency which requires go but go isn't installed (my wild guess here)

**Comment by aeneasr** [comment]
Ok this is definately related to missing golang. It requires a recent go version (>= 1.4.0)

**Comment by sauliusstasiukaitis** [comment]
+1

**Comment by aeneasr** [comment]
@stasiukaitis-saulius use terraform instead: https://www.google.de/search?q=terraform+cloud+foundry

**Comment by sauliusstasiukaitis** [comment]
@arekkas tx, will look at it.
