### ISSUE TITLE
fog cannot ssh into server

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-community-attic/inception-server#7]
```
Booting m1.small inception server... i-70644d1e
Confirming ssh access to server... /Users/drnic/.rvm/gems/ruby-1.9.3-p429/gems/fog-1.11.1/lib/fog/core/wait_for.rb:10:in `wait_for': The specified wait_for timeout (60 seconds) was exceeded (Fog::Errors::TimeoutError)
    from /Users/drnic/Projects/ruby/gems/inception-server/lib/inception/inception_server.rb:276:in `attach_persistent_disk'
    from /Users/drnic/Projects/ruby/gems/inception-server/lib/inception/inception_server.rb:67:in `create'
    from /Users/drnic/Projects/ruby/gems/inception-server/lib/inception/cli.rb:88:in `perform_deploy'
    from /Users/drnic/Projects/ruby/gems/inception-server/lib/inception/cli.rb:34:in `deploy'
```

Perhaps it doesn't have the private key path?

**Comment by drnic** [comment]
``` ruby
    def fog_server
      @fog_server ||= begin
        if server_id = provisioned["server_id"]
          fog_compute.servers.get(server_id)
        end
      end
    end
```

Does this setup ssh keys correctly?

**Comment by drnic** [comment]
Perhaps instead of using fog_compute below, use normal ssh:

``` ruby
        Fog.wait_for(60) { fog_server.sshable?(ssh_options) }
```

**Comment by drnic** [comment]
hmm, `ssh_options` does pass the private key

``` ruby
    def ssh_options
      {
        keys: [private_key_path]
      }
    end
```

**Comment by drnic** [comment]
```
$ ssh ubuntu@ec2-75-101-243-190.compute-1.amazonaws.com -i ~/.inception_server/ssh/inception 
The authenticity of host 'ec2-75-101-243-190.compute-1.amazonaws.com (75.101.243.190)' can't be established.
RSA key fingerprint is ea:db:e4:98:38:d8:ca:7c:0e:4c:f5:c5:92:64:3c:56.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'ec2-75-101-243-190.compute-1.amazonaws.com,75.101.243.190' (RSA) to the list of known hosts.
```

Perhaps `ssh_options` needs to ignore `Are you sure you want to continue connecting (yes/no)? yes`?

**Comment by drnic** [comment]
Seemed to be an issue with shite internet at hotel
