### ISSUE TITLE
[tags/v0.3.0] Exception: NameError: uninitialized constant Syck (ruby 2.2.0)

### ISSUE THREAD

**Issue by aeneasr** [cloudfoundry-community-attic/inception-server#71]
On a ubuntu/trusty32 virtual machine I did the following:

```
apt-get update
apt-get install curl git g++ build-essential -y
apt-get remove ruby --purge # we need ruby > 2.0.0
apt-get autoremove -y
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
curl -sSL https://get.rvm.io | bash -s stable --ruby
source /usr/loycal/rvm/scripts/rvm
touch /home/vagrant/.ssh/config
chown vagrant:vagrant /home/vagrant/.ssh/config

# As suggested by https://github.com/cloudfoundry-community/inception-server/issues/63
touch /root/.ssh/config
echo '
Host "ec2*.amazonaws.com"
  User ubuntu
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no' | tee -a /home/vagrant/.ssh/config /root/.ssh/config

cd /root
git clone https://github.com/cloudfoundry-community/inception-server.git
cd inception-server
git checkout tags/v0.3.0
gem install bundler
gem gem update --system
bundle
git config --global user.name "John Doe"
git config --global user.email johndoe@example.com
bundle exec bin/inception deploy
```

After entering my aws credentials and region eu-west-1 everything seemed to work fine until knife exited with an unexpected error:

```
WARNING: No knife configuration file found
Running Chef on ec2-52-16-***-***.eu-west-1.compute.amazonaws.com...
Checking Chef version...
ERROR: knife encountered an unexpected error
This may be a bug in the 'solo cook' knife command or plugin
Please collect the output of this command with the `-VV` option before filing a bug report.
Exception: NameError: uninitialized constant Syck
/usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/file_utils.rb:66:in `block in create_shell_runner': Command failed with status (100): [knife solo cook ubuntu@ec2-52-16-***-***.eu...] (RuntimeError)
    from /usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/file_utils.rb:57:in `call'
    from /usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/file_utils.rb:57:in `sh'
    from /root/inception-server/lib/inception/inception_server_cookbook.rb:39:in `knife_solo'
    from /root/inception-server/lib/inception/inception_server_cookbook.rb:26:in `block in converge'
    from /usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/fileutils.rb:127:in `chdir'
    from /usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/fileutils.rb:127:in `cd'
    from /root/inception-server/lib/inception/inception_server_cookbook.rb:25:in `converge'
    from /root/inception-server/lib/inception/cli.rb:143:in `converge_cookbooks'
    from /root/inception-server/lib/inception/cli.rb:35:in `deploy'
    from /usr/local/rvm/gems/ruby-2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /usr/local/rvm/gems/ruby-2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /usr/local/rvm/gems/ruby-2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /usr/local/rvm/gems/ruby-2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from bin/inception:8:in `<main>'
```

**Comment by aeneasr** [comment]
Okay, so it looks like using ruby-2.0.0 resolves this issue as this error does not appear any more.
