### ISSUE TITLE
Unable to copy stemcell to root image

### ISSUE THREAD

**Issue by frosenberg** [cloudfoundry-community-attic/inception-server#72]
I keep getting this error when running the deploy on the inception server. Any ideas?

I debugged a bit and I don't know that the `stemcell-copy.sh` script is supposed to do but `/dev/xvdg` does not exist. Where does it get the value from?

```
ubuntu@ip-172-31-12-199:~$ bosh-bootstrap deploy

Confirming: Using AWS EC2/eu-central-1

Confirming: Using address 10.0.0.4
Reusing security group ssh-vpc-f2c4069b for the VPC
 -> no additional ports opened
Reusing security group dns-server-vpc-f2c4069b for the VPC
 -> no additional ports opened
Reusing security group bosh-vpc-f2c4069b for the VPC
 -> no additional ports opened

Confirming: Using key pair firstbosh
Determining stemcell image/file to use... /home/ubuntu/deployments/firstbosh/bosh-stemcell-2915-aws-xen-ubuntu-trusty-go_agent.tgz
bosh micro deployment firstbosh
Deployment set to '/home/ubuntu/deployments/firstbosh/micro_bosh.yml'
bosh -n micro deploy --update-if-exists /home/ubuntu/deployments/firstbosh/bosh-stemcell-2915-aws-xen-ubuntu-trusty-go_agent.tgz

Verifying stemcell...
File exists and readable                                     OK
Verifying tarball...
Read tarball                                                 OK
Manifest exists                                              OK
Stemcell image file                                          OK
Stemcell properties                                          OK

Stemcell info
-------------
Name:    bosh-aws-xen-ubuntu-trusty-go_agent
Version: 2915

  Started deploy micro bosh
  Started deploy micro bosh > Unpacking stemcell. Done (00:00:09)
  Started deploy micro bosh > Uploading stemcellcreate stemcell failed: Unable to copy stemcell root image: command 'sudo -n /home/ubuntu/.gem/ruby/1.9.3/gems/bosh_aws_cpi-1.2915.0/scripts/stemcell-copy.sh /tmp/d20150410-2045-10udg24/sc-20150410-2045-1rx7hon/image /dev/xvdg 2>&1' failed with exit code 1:
/home/ubuntu/.gem/ruby/1.9.3/gems/bosh_aws_cpi-1.2915.0/lib/cloud/aws/stemcell_creator.rb:71:in `rescue in copy_root_image'
/home/ubuntu/.gem/ruby/1.9.3/gems/bosh_aws_cpi-1.2915.0/lib/cloud/aws/stemcell_creator.rb:54:in `copy_root_image'
/home/ubuntu/.gem/ruby/1.9.3/gems/bosh_aws_cpi-1.2915.0/lib/cloud/aws/stemcell_creator.rb:19:in `create'
/home/ubuntu/.gem/ruby/1.9.3/gems/bosh_aws_cpi-1.2915.0/lib/cloud/aws/cloud.rb:431:in `block in create_stemcell'
/home/ubuntu/.gem/ruby/1.9.3/gems/bosh_common-1.2915.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/home/ubuntu/.gem/ruby/1.9.3/gems/bosh_aws_cpi-1.2915.0/lib/cloud/aws/cloud.rb:411:in `create_stemcell'
/home/ubuntu/.gem/ruby/1.9.3/gems/bosh_cli_plugin_micro-1.2915.0/lib/bosh/deployer/instance_manager.rb:228:in `block (2 levels) in create_stemcell'
/home/ubuntu/.gem/ruby/1.9.3/gems/bosh_cli_plugin_micro-1.2915.0/lib/bosh/deployer/instance_manager.rb:85:in `step'
/home/ubuntu/.gem/ruby/1.9.3/gems/bosh_cli_plugin_micro-1.2915.0/lib/bosh/deployer/instance_manager.rb:227:in `block in create_stemcell'
/opt/rubies/1.9.3-p392/lib/ruby/1.9.1/tmpdir.rb:83:in `mktmpdir'
/home/ubuntu/.gem/ruby/1.9.3/gems/bosh_cli_plugin_micro-1.2915.0/lib/bosh/deployer/instance_manager.rb:213:in `create_stemcell'
/home/ubuntu/.gem/ruby/1.9.3/gems/bosh_cli_plugin_micro-1.2915.0/lib/bosh/deployer/instance_manager.rb:118:in `create'
/home/ubuntu/.gem/ruby/1.9.3/gems/bosh_cli_plugin_micro-1.2915.0/lib/bosh/deployer/instance_manager.rb:98:in `block in create_deployment'
/home/ubuntu/.gem/ruby/1.9.3/gems/bosh_cli_plugin_micro-1.2915.0/lib/bosh/deployer/instance_manager.rb:92:in `with_lifecycle'
/home/ubuntu/.gem/ruby/1.9.3/gems/bosh_cli_plugin_micro-1.2915.0/lib/bosh/deployer/instance_manager.rb:98:in `create_deployment'
/home/ubuntu/.gem/ruby/1.9.3/gems/bosh_cli_plugin_micro-1.2915.0/lib/bosh/cli/commands/micro.rb:179:in `perform'
/home/ubuntu/.gem/ruby/1.9.3/gems/bosh_cli-1.2915.0/lib/cli/command_handler.rb:57:in `run'
/home/ubuntu/.gem/ruby/1.9.3/gems/bosh_cli-1.2915.0/lib/cli/runner.rb:56:in `run'
/home/ubuntu/.gem/ruby/1.9.3/gems/bosh_cli-1.2915.0/bin/bosh:16:in `<top (required)>'
/home/ubuntu/.gem/ruby/1.9.3/bin/bosh:23:in `load'
/home/ubuntu/.gem/ruby/1.9.3/bin/bosh:23:in `<main>'
/opt/rubies/1.9.3-p392/lib/ruby/1.9.1/rake/file_utils.rb:53:in `block in create_shell_runner': Command failed with status (1): [bosh -n micro deploy --update-if-exists /h...] (RuntimeError)
    from /opt/rubies/1.9.3-p392/lib/ruby/1.9.1/rake/file_utils.rb:45:in `call'
    from /opt/rubies/1.9.3-p392/lib/ruby/1.9.1/rake/file_utils.rb:45:in `sh'
    from /home/ubuntu/.gem/ruby/1.9.3/gems/bosh-bootstrap-0.16.2/lib/bosh-bootstrap/cli/helpers/bundle.rb:18:in `block in run'
    from /home/ubuntu/.gem/ruby/1.9.3/gems/bundler-1.9.2/lib/bundler.rb:247:in `block in with_clean_env'
    from /home/ubuntu/.gem/ruby/1.9.3/gems/bundler-1.9.2/lib/bundler.rb:234:in `with_original_env'
    from /home/ubuntu/.gem/ruby/1.9.3/gems/bundler-1.9.2/lib/bundler.rb:240:in `with_clean_env'
    from /home/ubuntu/.gem/ruby/1.9.3/gems/bosh-bootstrap-0.16.2/lib/bosh-bootstrap/cli/helpers/bundle.rb:16:in `run'
    from /home/ubuntu/.gem/ruby/1.9.3/gems/bosh-bootstrap-0.16.2/lib/bosh-bootstrap/microbosh.rb:54:in `block in deploy_or_update'
    from /opt/rubies/1.9.3-p392/lib/ruby/1.9.1/fileutils.rb:125:in `chdir'
    from /opt/rubies/1.9.3-p392/lib/ruby/1.9.1/fileutils.rb:125:in `cd'
    from /home/ubuntu/.gem/ruby/1.9.3/gems/bosh-bootstrap-0.16.2/lib/bosh-bootstrap/microbosh.rb:52:in `deploy_or_update'
    from /home/ubuntu/.gem/ruby/1.9.3/gems/bosh-bootstrap-0.16.2/lib/bosh-bootstrap/microbosh.rb:42:in `block in deploy'
    from /opt/rubies/1.9.3-p392/lib/ruby/1.9.1/fileutils.rb:125:in `chdir'
    from /opt/rubies/1.9.3-p392/lib/ruby/1.9.1/fileutils.rb:125:in `cd'
    from /home/ubuntu/.gem/ruby/1.9.3/gems/bosh-bootstrap-0.16.2/lib/bosh-bootstrap/microbosh.rb:40:in `deploy'
    from /home/ubuntu/.gem/ruby/1.9.3/gems/bosh-bootstrap-0.16.2/lib/bosh-bootstrap/cli/commands/deploy.rb:77:in `perform_microbosh_deploy'
    from /home/ubuntu/.gem/ruby/1.9.3/gems/bosh-bootstrap-0.16.2/lib/bosh-bootstrap/cli/commands/deploy.rb:24:in `perform'
    from /home/ubuntu/.gem/ruby/1.9.3/gems/bosh-bootstrap-0.16.2/lib/bosh-bootstrap/thor_cli.rb:11:in `deploy'
    from /home/ubuntu/.gem/ruby/1.9.3/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /home/ubuntu/.gem/ruby/1.9.3/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /home/ubuntu/.gem/ruby/1.9.3/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /home/ubuntu/.gem/ruby/1.9.3/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /home/ubuntu/.gem/ruby/1.9.3/gems/bosh-bootstrap-0.16.2/bin/bosh-bootstrap:13:in `<top (required)>'
    from /home/ubuntu/.gem/ruby/1.9.3/bin/bosh-bootstrap:23:in `load'
    from /home/ubuntu/.gem/ruby/1.9.3/bin/bosh-bootstrap:23:in `<main>'
ubuntu@ip-172-31-12-199:~$ 
```

**Comment by aetelani** [comment]
Yeah, seeing this too. any ideas how to get it working?
